package core.api.metadata;

import cpw.mods.fml.common.ModContainer;

import java.util.List;

/**
 * Created by Master801 on 10/3/2014.
 * @author Master801
 */
public interface IMetadata {

    List<String> getAuthorList();

    boolean isAutoGenerated();

    List<ModContainer> getChildMods();

    List<String> getCredits();

    String getDescription();

    String getLogo();

    String getModID();

    String getModName();

    String getParentMod();

    String[] getScreenShots();

    String getUpdateURL();

    String getURL();

    String getModVersion();

}
