package core.common.resources;

import core.Core;
import core.api.common.mod.IUpdateableMod;
import core.api.metadata.IMetadata;
import core.helpers.ChatHelper;
import core.helpers.ExternalModsHelper;
import core.helpers.ModHelper;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.ModContainer;
import net.minecraft.util.EnumChatFormatting;

import java.util.ArrayList;
import java.util.List;

public class CoreMetadata implements IMetadata {

    @Override
    public List<String> getAuthorList() {
        final List<String> authorList = new ArrayList<String>();
        authorList.add(ChatHelper.colourString(EnumChatFormatting.DARK_AQUA, "Master801"));
        return authorList;
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public List<ModContainer> getChildMods() {
        final List<ModContainer> list = new ArrayList<ModContainer>();
        for(Class classes : ModHelper.getAllModClasses()) {
            ModContainer gotContainer = Loader.instance().getIndexedModList().get(ExternalModsHelper.getModIDFromClass(classes));
            if (gotContainer != null) {
                list.add(gotContainer);
            }
        }
        return list;
    }

    @Override
    public List<String> getCredits() {
        final List<String> list = new ArrayList<String>();
        list.add(ChatHelper.colourString(EnumChatFormatting.LIGHT_PURPLE, "CastielAngelow"));
        list.add(ChatHelper.colourString(EnumChatFormatting.LIGHT_PURPLE, "RSQ/SynthTones/whatever other aliases he uses"));
        list.add(ChatHelper.colourString(EnumChatFormatting.LIGHT_PURPLE, "Anyone that didn't give up on me while I was depressed."));
        return list;
    }

    @Override
    public String getDescription() {
        return ChatHelper.colourString(EnumChatFormatting.DARK_PURPLE, "A modding library for all of Master801's mods.");
    }

    @Override
    public String getLogo() {
        return "/mcplogo.png";
    }

    @Override
    public String getModID() {
        return ChatHelper.colourString(EnumChatFormatting.DARK_RED, CoreResources.CORE_MODID);
    }

    @Override
    public String getModName() {
        return ChatHelper.colourString(EnumChatFormatting.DARK_RED, CoreResources.CORE_NAME);
    }

    @Override
    public String getParentMod() {
        return null;
    }

    @Override
    public String[] getScreenShots() {
        return new String[0];
    }

    @Override
    public String getUpdateURL() {
        return ((IUpdateableMod)Core.instance).getUpdateURL();
    }

    @Override
    public String getURL() {
        return "";
    }

    @Override
    public String getModVersion() {
        return ChatHelper.colourString(EnumChatFormatting.AQUA, CoreResources.CORE_VERSION);
    }
}
